export const Types = {
    PRODUCT_ID: 'PRODUCT_ID',
    SET_PRODUCT: 'SET_PRODUCT',
    SET_AMOUNT: 'SET_AMOUNT',
    SET_INTERET: 'SET_INTERET',
    SET_MONTHS: 'SET_MONTHS',
    SET_DATA: 'SET_DATA',
    ACTUAL_DATA: 'ACTUAL_DATA',
    TOTAL: 'TOTAL',
}